name: Auto Approve Free Transactions

on:
  workflow_dispatch:   # manual run button
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Auto Approval Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python auto_approve.py
